apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-tutorialsonline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-tutorialsonline
    app.kubernetes.io/part-of: spring-boot-app-t1
  name: angular-15-client-tutorialsonline
spec:
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app.kubernetes.io/instance: angular-15-client-tutorialsonline
status:
  loadBalancer: {}
